spring.application.name=flashcard-app

spring.datasource.url=jdbc:postgresql://db.twlsavmpjgxuxwszectk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=%5@SBSnaagAX#3m

# Tell Spring Boot this is PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Do NOT let Hibernate touch the existing Supabase schema
spring.jpa.hibernate.ddl-auto=none

# Show SQL in logs so you can see exactly what is sent
spring.jpa.show-sql=true